### ISSUE TITLE
Regarder ce qu'on peut réutiliser (liens Alexandre)

### ISSUE THREAD

**Issue by Plouc314** [GenoRobotics-EPFL/Identification#2]

**Comment by AlexMlld** [comment]
SequenceServer : C'est en javascript mais plutôt complet et assez intéressant
https://github.com/wurmlab/sequenceserver

ElasticBlast : Pas testé encore, fonctionne avec Cloud Blast et c'est en python donc à voir
https://github.com/ncbi/elastic-blast

IgBLAST-biobox: N'est plus mis-à -jour depuis longtemps mais on peut regarder si il y a des trucs a récupérer
https://github.com/williamdlees/IgBLAST_BioBox

Blast-Mining: Projet en python assez interessant aussi à voir ce qu'on peut récupérer ou modifier pour potentiellement l'utiliser
https://github.com/NuruddinKhoiry/blastMining
